# Generated by Django 2.1.7 on 2019-03-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RPSer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rpser_last', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors'), ('N', 'None')], max_length=1)),
                ('user_last', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors'), ('N', 'None')], max_length=1)),
                ('rpser_next', models.CharField(choices=[('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors'), ('N', 'None')], max_length=1)),
                ('count', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.AddField(
            model_name='brain',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RPSer.User'),
        ),
        migrations.AlterUniqueTogether(
            name='brain',
            unique_together={('id', 'rpser_last', 'user_last', 'rpser_next')},
        ),
    ]
