# Generated by Django 2.1.7 on 2019-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPSer', '0003_auto_20190322_2154'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brain',
            name='RPSer_brain_usernam_b44606_idx',
        ),
        migrations.RenameField(
            model_name='brain',
            old_name='username',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='w_l',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='brain',
            index=models.Index(fields=['userid', 'rpser_last', 'user_last'], name='RPSer_brain_userid__f50b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'username', 'w_l', 'count'], name='RPSer_user_id_f27158_idx'),
        ),
    ]
