# Generated by Django 2.1.7 on 2019-03-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPSer', '0004_auto_20190325_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brain',
            unique_together={('userid', 'rpser_last', 'user_last', 'rpser_next')},
        ),
    ]
